#!/usr/bin/env bash
# Render a publication-style snapshot of a system in a project directory.
#
# Usage: ./scripts/render-snapshot.sh <gro> <out.tga> [coloring-tcl]
# Example:
#   ./scripts/render-snapshot.sh \
#       proj-0/systems/final-results/final.gro \
#       badcy-cured.tga \
#       custom-colors.tcl
#
# The .gro must sit alongside a .viz.psf, .viz.tcl, and (optionally) a
# .viz.macros.tcl carrying the constituent-keyed atomselect macros.
#
# An optional third argument is a TCL fragment sourced *after* the viz
# helpers but *before* the render — use it for per-system camera
# adjustments, residue-color overrides, etc.  See the bottom of this
# file for the default coloring rules and a starter snippet.
#
# The output is rendered via Tachyon (internal to VMD) at 1200x900;
# convert to PNG afterwards with `convert out.tga out.png`.  Tachyon
# files are roughly proportional to surface area; expect a couple MB
# per render for a ~10k-atom system.

set -euo pipefail

GRO="${1:?Usage: render-snapshot.sh <gro> <out.tga> [coloring-tcl]}"
OUT="${2:?Usage: render-snapshot.sh <gro> <out.tga> [coloring-tcl]}"
COLORING="${3:-}"

if [[ ! -f "$GRO" ]]; then
    echo "ERROR: $GRO not found" >&2
    exit 1
fi

# Resolve to absolute so the walk-up logic below has a real path to
# work with (relative ./foo.gro otherwise gives DIR='.', which the
# loop guard treats as already-at-the-root).
GRO="$(realpath "$GRO")"
DIR="$(dirname "$GRO")"
STEM="$(basename "$GRO" .gro)"

# Look for a viz.psf colocated with the gro (the final-results case);
# if not found, walk up to proj-N/systems/final-results and use that
# pair *only if* the gro and psf describe the same atom count.  In any
# other case (typically a stage gro like densification's, where the
# atom count differs from the post-cure / post-repair final topology),
# fall back to letting VMD auto-bond the gro alone.
PSF="$DIR/$STEM.viz.psf"
TCL="$DIR/$STEM.viz.tcl"
MACROS="$DIR/$STEM.viz.macros.tcl"

if [[ ! -f "$PSF" ]]; then
    ROOT="$DIR"
    while [[ "$ROOT" != "/" && "$ROOT" != "." ]]; do
        if [[ -f "$ROOT/systems/final-results/final.viz.psf" ]]; then
            CAND_PSF="$ROOT/systems/final-results/final.viz.psf"
            CAND_TCL="$ROOT/systems/final-results/final.viz.tcl"
            CAND_MACROS="$ROOT/systems/final-results/final.viz.macros.tcl"
            # Match atom counts: gro line 2 is the atom count; psf has
            # "<count> !NATOM" on a header line.
            GRO_N="$(awk 'NR==2 {print $1; exit}' "$GRO")"
            PSF_N="$(awk '/!NATOM/ {print $1; exit}' "$CAND_PSF")"
            if [[ "$GRO_N" == "$PSF_N" ]]; then
                PSF="$CAND_PSF"
                TCL="$CAND_TCL"
                MACROS="$CAND_MACROS"
            fi
            break
        fi
        ROOT="$(dirname "$ROOT")"
    done
fi

# Emit the driver TCL into a tempfile so VMD's -e can source it.
DRIVER="$(mktemp /tmp/render-snapshot.XXXXXX.tcl)"
trap 'rm -f "$DRIVER"' EXIT

cat > "$DRIVER" <<TCL
# Auto-generated by scripts/render-snapshot.sh
package require topotools

TCL

if [[ -f "$PSF" ]]; then
    cat >> "$DRIVER" <<TCL
# Cured-network mode: PSF + GRO pair with matching atom counts.
# htpolynet's viz.tcl trims bonds longer than 3 Å so PBC-crossing
# bonds in a crosslinked network don't draw as long bonds.  We do
# NOT source the viz.macros.tcl: it defines per-constituent atomselect
# macros named after each residue (BPA, TAZ, ...) which shadow the
# built-in 'resname' keyword and make 'resname BPA' fail to parse.
# Coloring snippets should use 'resname <NAME>' selectors instead.
mol new "$PSF" type psf waitfor all
mol addfile "$GRO" type gro waitfor all
TCL
    # Inline the viz.tcl manually so the auto-source of macros.tcl is
    # bypassed.  The viz.tcl just defines + immediately invokes a
    # htpolynet_trim_pbc_bonds proc; sourcing it directly would also
    # auto-load the macros.  Easier to call the proc by hand here.
    cat >> "$DRIVER" <<'TCL'
package require topotools
# Inline a minimal PBC-trim: drop any bond longer than 3 Å from the
# display so wrap-around bonds don't draw as long lines.  Matches what
# htpolynet's viz.tcl does, without the macros side effect.
set _bl [topo getbondlist both]
set _keep [list]
foreach _b $_bl {
    lassign $_b _i _j _t _o
    if {[measure bond [list $_i $_j]] <= 3.0} { lappend _keep $_b }
}
topo setbondlist both $_keep
unset _bl _keep _b _i _j _t _o
TCL
else
    cat >> "$DRIVER" <<TCL
# Stage / pre-cure mode: no matching PSF available, so VMD infers
# bonds from interatomic distances in the gro itself.  The bond
# inference uses VMD's default radii table and produces a reasonable
# molecular drawing for unreacted monomers.
mol new "$GRO" type gro waitfor all autobonds yes
TCL
fi

cat >> "$DRIVER" <<TCL

# Default coloring: light-grey backbone + CPK on reactive sites if
# any.  Override in the per-system coloring snippet below.
mol delrep 0 top
mol representation Licorice 0.2 12.0 12.0
mol color ColorID 6
mol selection all
mol addrep top

# Render setup: white background, perspective, top-down view.
display projection Perspective
display nearclip set 0.01
display depthcue off
color Display Background white
display rendermode GLSL

# Per-system overrides (camera framing, colors, additional reps).
TCL

if [[ -n "$COLORING" && -f "$COLORING" ]]; then
    cat "$COLORING" >> "$DRIVER"
fi

cat >> "$DRIVER" <<'TCL'

# Fit the box in the viewport, default rotation.
display resetview
rotate x by -60
rotate y by 30
scale by 0.85

# Tachyon render to the specified path.
render Tachyon $env(SNAPSHOT_OUT) \
    "$env(TACHYON)" -aasamples 12 %s -format TARGA -res 1200 900 -o %s

quit
TCL

# Pick up the local tachyon binary; fall back to "tachyon" on PATH.
TACHYON_BIN="${TACHYON:-$(command -v tachyon 2>/dev/null || echo tachyon)}"

echo "rendering $GRO → $OUT (via $PSF)"
SNAPSHOT_OUT="$OUT" TACHYON="$TACHYON_BIN" \
    vmd -dispdev text -e "$DRIVER" </dev/null > /tmp/render-snapshot.log 2>&1

if [[ ! -f "$OUT" ]]; then
    echo "ERROR: render failed; see /tmp/render-snapshot.log" >&2
    tail -20 /tmp/render-snapshot.log >&2
    exit 1
fi

echo "wrote $OUT"
