name: Sphinx build

on:
  push:
    paths:
      - "docs/**"
      - "src/**"
      - ".github/workflows/sphinx.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install package
      run: python -m pip install --prefer-binary -e .

    - name: Install docs dependencies
      run: python -m pip install --prefer-binary -r docs/requirements.txt

    - name: Build HTML docs
      run: python -m sphinx -b html docs/source docs/build/html

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
